apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: connections-metric-hpa
spec:
  scaleTargetRef:
    # Point at the connections metric app
    apiVersion: apps/v1
    kind: Deployment
    name: connection-metrics-app
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Pods # use Pods metric, since the metric is attached to the pod
    pods:
      targetAverageValue: 5
      metricName: connection_count
