apiVersion: v1
kind: Service
metadata:
  name: connections-metric-svc
  labels:
    hasCustomMetrics: 'true'
spec:
  selector:
    app: connection-metrics-server
  ports:
  - port: 3000
  type: NodePort
