apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-apps-service-monitor
  namespace: monitoring
  labels:
    release: prom-op
spec:
  endpoints:
  - targetPort: 3000
    honorLabels: true
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      hasCustomMetrics: 'true'
